### ISSUE TITLE
JSON error when marking submission as spam

### ISSUE THREAD

**Issue by boboldehampsink** [craftcms/guest-entries#46] opened 2019-02-14 15:31 UTC
When marking a submission as spam in an application/json request, the plugin tries to set the (at that point) non-existing author: https://github.com/craftcms/guest-entries/blob/4abfd96696e1e63ee971ae8abd70b4c92f244d27/src/controllers/SaveController.php#L167

This results in an error

**Comment by brandonkelly** [comment] 2019-02-14 18:37
The author should have been assigned from `_populateEntryModel()` regardless of whether the submission was labeled as spam or not. You’re sure you’re not also getting an error when the submission is _not_ spam?

**Comment by boboldehampsink** [comment] 2019-02-15 07:07
No in that case it succeeds

**Comment by brandonkelly** [comment] 2019-02-15 17:46
Can you step through that `_populateEntryModel()` code and see why the author isn’t getting set in that case? Or maybe it is, but the plugin that’s marking the submission as spam is clearing it out?

**Comment by boboldehampsink** [comment] 2019-02-16 10:43
Mmm for some reason it had saved a non-existing uid. When simply saving the guest entries settings again the project.yaml changed and contained a new uid. Now everything works. Thanks anyway!

**Comment by boboldehampsink** [comment] 2019-02-16 10:48
After that conclusion it started happening to me again. I found that the saved UID is actually from the `elements` table while the `_populateEntryModel()` function looks in the `users` table.

**Comment by brandonkelly** [comment] 2019-02-24 14:25
Doh, OK so authors just aren’t ever getting set correctly. Thanks!

**Comment by brandonkelly** [comment] 2019-02-24 14:48
This is a duplicate of #43, and fixed in v2.2.3.

**Closed by brandonkelly** 2019-02-24 14:48 UTC
